# Site settings
title: Jayden's Portfolio
description: A portfolio showcasing projects I've worked on, and my skills

# User settings
username: Jayden Charbonneau
user_description: |
Software Engineer & Game Designer with years of full-stack programming experience, both independent and working with a team.
Winner of a game-jam at RDC-2020 for the title "Most Creative Gameplay". Currently working towards running my own studio, with the
hopes of expanding it to AAA levels. Always eager to expand my
capabilities as a programmer, and I love constructing immersive worlds
that other people can enjoy.

user_title: Software Engineer, Game Developer & Game Designer
email: BinaryByte.DEV@gmail.com
twitter_username: Noble_Draconian
github_username: NobleDraconian

exclude: ['package.json', 'src' , 'node_modules']
